codecov:
  require_ci_to_pass: true

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: true

coverage:
  precision: 2
  round: down
  range: "70...90"
  status:
    project:
      default:
        target: 80%
        threshold: 1%
    patch:
      default:
        target: 80%
